/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Label;

/**
 *
 * @author diana
 */
public class BoletoVista extends javax.swing.JPanel {

    /**
     * Creates new form BoletoVista
     */
    public BoletoVista() {
        initComponents();
    }

    public Label getTxtAsiento() {
        return txtAsiento;
    }

    public void setTxtAsiento(Label txtAsiento) {
        this.txtAsiento = txtAsiento;
    }

    public Label getTxtFecha() {
        return txtFecha;
    }

    public void setTxtFecha(Label txtFecha) {
        this.txtFecha = txtFecha;
    }

    public Label getTxtHora() {
        return txtHora;
    }

    public void setTxtHora(Label txtHora) {
        this.txtHora = txtHora;
    }

    public Label getTxtId() {
        return txtId;
    }

    public void setTxtId(Label txtId) {
        this.txtId = txtId;
    }

    public Label getTxtNombreObra() {
        return txtNombreObra;
    }

    public void setTxtNombreObra(Label txtNombreObra) {
        this.txtNombreObra = txtNombreObra;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBoletos = new java.awt.Panel();
        txtId = new java.awt.Label();
        txtNombreObra = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        txtAsiento = new java.awt.Label();
        txtHora = new java.awt.Label();
        label9 = new java.awt.Label();
        txtFecha = new java.awt.Label();
        label11 = new java.awt.Label();

        panelBoletos.setBackground(new java.awt.Color(25, 43, 55));
        panelBoletos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setAlignment(java.awt.Label.CENTER);
        txtId.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(213, 218, 222));
        txtId.setText("01245687");
        panelBoletos.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtNombreObra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNombreObra.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreObra.setText("Alicia en el país de las Maravillas");
        panelBoletos.add(txtNombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Imagen1.png"))); // NOI18N
        panelBoletos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 100));

        txtAsiento.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        txtAsiento.setForeground(new java.awt.Color(255, 153, 0));
        txtAsiento.setText("A1");
        panelBoletos.add(txtAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        txtHora.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setText("15:00 hrs");
        panelBoletos.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("FUNCIÓN:");
        panelBoletos.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        txtFecha.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("12/12/12");
        panelBoletos.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        label11.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 153, 0));
        label11.setText("CHACHITA");
        panelBoletos.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private java.awt.Label label11;
    private java.awt.Label label9;
    private java.awt.Panel panelBoletos;
    private java.awt.Label txtAsiento;
    private java.awt.Label txtFecha;
    private java.awt.Label txtHora;
    private java.awt.Label txtId;
    private java.awt.Label txtNombreObra;
    // End of variables declaration//GEN-END:variables
}
