/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author 
 */
public class Boleto extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBoleto
     */
    public Boleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textArea4 = new java.awt.TextArea();
        jButton2 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel5 = new javax.swing.JLabel();
        LabelAsiento = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Elegir Asientos");
        jButton2.setToolTipText("Modificar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boleto");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(25, 43, 55));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(213, 218, 222));
        label5.setText("01245687");
        panel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        label6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Alicia en el país de las Maravillas");
        panel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Imagen1.png"))); // NOI18N
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 100));

        LabelAsiento.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        LabelAsiento.setForeground(new java.awt.Color(255, 153, 0));
        LabelAsiento.setText("A1");
        panel1.add(LabelAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setText("15:00 hrs");
        panel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("FUNCIÓN:");
        panel1.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("12/12/12");
        panel1.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        label11.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 153, 0));
        label11.setText("CHACHITA");
        panel1.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 240));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label LabelAsiento;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.TextArea textArea4;
    // End of variables declaration//GEN-END:variables
}
