/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.Date;
import java.util.Calendar;

import com.toedter.calendar.JDateChooser;

/**
 *
 * @author diana
 */
public class ElegirFuncion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaElegirFuncion
     */
    public ElegirFuncion() {
        initComponents();
        calendar.setMinSelectableDate(new java.util.Date());
        Calendar dateToday = Calendar.getInstance(); 
        calendar.setDate(new Date(dateToday.getTimeInMillis())); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel19 = new java.awt.Panel();
        panel18 = new java.awt.Panel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegresarMenu = new javax.swing.JButton();
        txtResumen = new java.awt.TextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnElegirAsientos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboBoxObra = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboBoxHorario = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        panel5 = new java.awt.Panel();
        calendar = new com.toedter.calendar.JDateChooser();
        panel4 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elegir Función");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel19.setBackground(new java.awt.Color(255, 255, 254));
        panel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel18.setBackground(new java.awt.Color(25, 43, 55));

        jLabel21.setBackground(new java.awt.Color(25, 43, 55));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Elegir Función");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menú");

        btnRegresarMenu.setBackground(new java.awt.Color(25, 43, 55));
        btnRegresarMenu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/regreso2.png"))); // NOI18N
        btnRegresarMenu.setToolTipText("Regresar");
        btnRegresarMenu.setBorder(null);

        javax.swing.GroupLayout panel18Layout = new javax.swing.GroupLayout(panel18);
        panel18.setLayout(panel18Layout);
        panel18Layout.setHorizontalGroup(
            panel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel18Layout.setVerticalGroup(
            panel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        panel19.add(panel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 50));

        txtResumen.setEditable(false);
        txtResumen.setEnabled(false);
        panel19.add(txtResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 310, 130));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 43, 55));
        jLabel5.setText("Obra");
        panel19.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 43, 55));
        jLabel6.setText("Resumen temático");
        panel19.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 160, -1));

        btnElegirAsientos.setBackground(new java.awt.Color(255, 102, 0));
        btnElegirAsientos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnElegirAsientos.setForeground(new java.awt.Color(255, 255, 255));
        btnElegirAsientos.setText("Elegir Asientos");
        btnElegirAsientos.setToolTipText("Modificar");
        panel19.add(btnElegirAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 130, 30));

        btnCancelar.setBackground(new java.awt.Color(25, 43, 55));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        panel19.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 130, 30));

        comboBoxObra.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxObra.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxObra.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxObra.setToolTipText("");
        panel19.add(comboBoxObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 43, 55));
        jLabel13.setText("Fecha");
        panel19.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 43, 55));
        jLabel14.setText("Precio");
        panel19.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        comboBoxHorario.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxHorario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxHorario.setForeground(new java.awt.Color(0, 0, 0));
        panel19.add(comboBoxHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 43, 55));
        jLabel15.setText("Horario");
        panel19.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        panel19.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, -1));

        panel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel19.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 690, 30));

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setForeground(new java.awt.Color(0, 0, 0));
        panel19.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, -1));

        getContentPane().add(panel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 310));

        panel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 690, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirFuncion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirFuncion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElegirAsientos;
    private javax.swing.JButton btnRegresarMenu;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JComboBox<String> comboBoxHorario;
    private javax.swing.JComboBox<String> comboBoxObra;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.Panel panel18;
    private java.awt.Panel panel19;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private javax.swing.JTextField txtPrecio;
    private java.awt.TextArea txtResumen;
    // End of variables declaration//GEN-END:variables
    
    public javax.swing.JButton getBtnElegirAsientos() {
        return btnElegirAsientos;
    }

    public void setBtnElegirAsientos(javax.swing.JButton btnElegirAsientos) {
        this.btnElegirAsientos = btnElegirAsientos;
    }

    public javax.swing.JButton getBtnRegresarMenu() {
        return btnRegresarMenu;
    }

    public void setBtnRegresarMenu(javax.swing.JButton btnRegresarMenu) {
        this.btnRegresarMenu = btnRegresarMenu;
    }

    public javax.swing.JComboBox<String> getComboBoxHorario() {
        return comboBoxHorario;
    }

    public void setComboBoxHorario(javax.swing.JComboBox<String> comboBoxHorario) {
        this.comboBoxHorario = comboBoxHorario;
    }

    public javax.swing.JComboBox<String> getComboBoxObra() {
        return comboBoxObra;
    }

    public void setComboBoxObra(javax.swing.JComboBox<String> comboBoxObra) {
        this.comboBoxObra = comboBoxObra;
    }

    public javax.swing.JButton getCancelar() {
        return btnCancelar;
    }

    public void setCancelar(javax.swing.JButton jButton1) {
        this.btnCancelar = jButton1;
    }

    public java.awt.TextArea getTxtResumen() {
        return txtResumen;
    }

    public void setTxtResumen(java.awt.TextArea textArea2) {
        this.txtResumen = textArea2;
    }

    public javax.swing.JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public void setTxtPrecio(javax.swing.JTextField txtPrecio) {
        this.txtPrecio = txtPrecio;
    }

    public JDateChooser getCalendar() {
        return calendar;
    }

    public void setCalendar(JDateChooser calendar) {
        this.calendar = calendar;
    }
    
}
