/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JCheckBox;

/**
 *
 * @author diana
 */
public class ElegirAsiento extends javax.swing.JFrame {

    /**
     * Creates new form VentanaElegirAsiento
     */    
    public ElegirAsiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        b2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        b1 = new javax.swing.JCheckBox();
        b3 = new javax.swing.JCheckBox();
        b4 = new javax.swing.JCheckBox();
        b6 = new javax.swing.JCheckBox();
        a2 = new javax.swing.JCheckBox();
        a1 = new javax.swing.JCheckBox();
        a6 = new javax.swing.JCheckBox();
        a7 = new javax.swing.JCheckBox();
        a12 = new javax.swing.JCheckBox();
        a11 = new javax.swing.JCheckBox();
        a13 = new javax.swing.JCheckBox();
        a8 = new javax.swing.JCheckBox();
        a15 = new javax.swing.JCheckBox();
        a5 = new javax.swing.JCheckBox();
        a10 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c1 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c12 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c15 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        b8 = new javax.swing.JCheckBox();
        b7 = new javax.swing.JCheckBox();
        b9 = new javax.swing.JCheckBox();
        b10 = new javax.swing.JCheckBox();
        b12 = new javax.swing.JCheckBox();
        b11 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        c4 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c14 = new javax.swing.JCheckBox();
        c13 = new javax.swing.JCheckBox();
        a14 = new javax.swing.JCheckBox();
        a9 = new javax.swing.JCheckBox();
        a4 = new javax.swing.JCheckBox();
        a3 = new javax.swing.JCheckBox();
        b5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elegir asientos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 254));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(25, 43, 55));

        jLabel5.setBackground(new java.awt.Color(255, 51, 0));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio a pagar: $");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 0));
        b2.setText("B2");
        b2.setToolTipText("");
        b2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b2.setRolloverEnabled(false);
        b2.setSelectedIcon(b1.getSelectedIcon());
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        panel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setToolTipText("Aceptar");
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 120, 32));

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceptar");
        jButton2.setToolTipText("Aceptar");
        jButton2.setRolloverEnabled(false);
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 120, 32));

        jLabel7.setBackground(new java.awt.Color(255, 51, 0));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Monto a pagar: ");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.setFocusable(false);
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 160, -1));

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 0));
        b1.setText("B1");
        b1.setToolTipText("");
        b1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b1.setRolloverEnabled(false);
        b1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoSeleccionado.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        panel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 0));
        b3.setText("B3");
        b3.setToolTipText("");
        b3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b3.setRolloverEnabled(false);
        b3.setSelectedIcon(b1.getSelectedIcon());
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        panel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 0));
        b4.setText("B4");
        b4.setToolTipText("");
        b4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b4.setRolloverEnabled(false);
        b4.setSelectedIcon(b1.getSelectedIcon());
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        panel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 0));
        b6.setText("B6");
        b6.setToolTipText("");
        b6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b6.setRolloverEnabled(false);
        b6.setSelectedIcon(b1.getSelectedIcon());
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        panel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a2.setForeground(new java.awt.Color(0, 0, 0));
        a2.setText("A2");
        a2.setToolTipText("");
        a2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a2.setRolloverEnabled(false);
        a2.setSelectedIcon(b1.getSelectedIcon());
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        panel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        a1.setBackground(new java.awt.Color(255, 255, 255));
        a1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setText("A1");
        a1.setToolTipText("A1");
        a1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a1.setRequestFocusEnabled(false);
        a1.setRolloverEnabled(false);
        a1.setSelectedIcon(b1.getSelectedIcon());
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        panel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        a6.setBackground(new java.awt.Color(255, 255, 255));
        a6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a6.setForeground(new java.awt.Color(0, 0, 0));
        a6.setText("A6");
        a6.setToolTipText("");
        a6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a6.setRolloverEnabled(false);
        a6.setSelectedIcon(b1.getSelectedIcon());
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        panel1.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        a7.setBackground(new java.awt.Color(255, 255, 255));
        a7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a7.setForeground(new java.awt.Color(0, 0, 0));
        a7.setText("A7");
        a7.setToolTipText("");
        a7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a7.setRolloverEnabled(false);
        a7.setSelectedIcon(b1.getSelectedIcon());
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a7ActionPerformed(evt);
            }
        });
        panel1.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        a12.setBackground(new java.awt.Color(255, 255, 255));
        a12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a12.setForeground(new java.awt.Color(0, 0, 0));
        a12.setText("A12");
        a12.setToolTipText("");
        a12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a12.setRolloverEnabled(false);
        a12.setSelectedIcon(b1.getSelectedIcon());
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });
        panel1.add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        a11.setBackground(new java.awt.Color(255, 255, 255));
        a11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a11.setForeground(new java.awt.Color(0, 0, 0));
        a11.setText("A11");
        a11.setToolTipText("");
        a11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a11.setRolloverEnabled(false);
        a11.setSelectedIcon(b1.getSelectedIcon());
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });
        panel1.add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        a13.setBackground(new java.awt.Color(255, 255, 255));
        a13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a13.setForeground(new java.awt.Color(0, 0, 0));
        a13.setText("A13");
        a13.setToolTipText("A1");
        a13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a13.setRolloverEnabled(false);
        a13.setSelectedIcon(b1.getSelectedIcon());
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a13ActionPerformed(evt);
            }
        });
        panel1.add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        a8.setBackground(new java.awt.Color(255, 255, 255));
        a8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a8.setForeground(new java.awt.Color(0, 0, 0));
        a8.setText("A8");
        a8.setToolTipText("");
        a8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a8.setRolloverEnabled(false);
        a8.setSelectedIcon(b1.getSelectedIcon());
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        panel1.add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        a15.setBackground(new java.awt.Color(255, 255, 255));
        a15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a15.setForeground(new java.awt.Color(0, 0, 0));
        a15.setText("A15");
        a15.setToolTipText("");
        a15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a15.setRolloverEnabled(false);
        a15.setSelectedIcon(b1.getSelectedIcon());
        a15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a15ActionPerformed(evt);
            }
        });
        panel1.add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        a5.setBackground(new java.awt.Color(255, 255, 255));
        a5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a5.setForeground(new java.awt.Color(0, 0, 0));
        a5.setText("A5");
        a5.setToolTipText("");
        a5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a5.setRolloverEnabled(false);
        a5.setSelectedIcon(b1.getSelectedIcon());
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        panel1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        a10.setBackground(new java.awt.Color(255, 255, 255));
        a10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a10.setForeground(new java.awt.Color(0, 0, 0));
        a10.setText("A10");
        a10.setToolTipText("A1");
        a10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a10.setRolloverEnabled(false);
        a10.setSelectedIcon(b1.getSelectedIcon());
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a10ActionPerformed(evt);
            }
        });
        panel1.add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 0, 0));
        c2.setText("C2");
        c2.setToolTipText("");
        c2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c2.setRolloverEnabled(false);
        c2.setSelectedIcon(b1.getSelectedIcon());
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        panel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 0, 0));
        c1.setText("C1");
        c1.setToolTipText("");
        c1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c1.setRolloverEnabled(false);
        c1.setSelectedIcon(b1.getSelectedIcon());
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        panel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        c6.setBackground(new java.awt.Color(255, 255, 255));
        c6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c6.setForeground(new java.awt.Color(0, 0, 0));
        c6.setText("C6");
        c6.setToolTipText("");
        c6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c6.setRolloverEnabled(false);
        c6.setSelectedIcon(b1.getSelectedIcon());
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        panel1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        c7.setBackground(new java.awt.Color(255, 255, 255));
        c7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c7.setForeground(new java.awt.Color(0, 0, 0));
        c7.setText("C7");
        c7.setToolTipText("");
        c7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c7.setRolloverEnabled(false);
        c7.setSelectedIcon(b1.getSelectedIcon());
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });
        panel1.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        c12.setBackground(new java.awt.Color(255, 255, 255));
        c12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c12.setForeground(new java.awt.Color(0, 0, 0));
        c12.setText("C12");
        c12.setToolTipText("");
        c12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c12.setRolloverEnabled(false);
        c12.setSelectedIcon(b1.getSelectedIcon());
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        panel1.add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        c11.setBackground(new java.awt.Color(255, 255, 255));
        c11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c11.setForeground(new java.awt.Color(0, 0, 0));
        c11.setText("C11");
        c11.setToolTipText("");
        c11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c11.setRolloverEnabled(false);
        c11.setSelectedIcon(b1.getSelectedIcon());
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        panel1.add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c3.setForeground(new java.awt.Color(0, 0, 0));
        c3.setText("C3");
        c3.setToolTipText("");
        c3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c3.setRolloverEnabled(false);
        c3.setSelectedIcon(b1.getSelectedIcon());
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        panel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        c8.setBackground(new java.awt.Color(255, 255, 255));
        c8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c8.setForeground(new java.awt.Color(0, 0, 0));
        c8.setText("C8");
        c8.setToolTipText("");
        c8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c8.setRolloverEnabled(false);
        c8.setSelectedIcon(b1.getSelectedIcon());
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });
        panel1.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        c15.setBackground(new java.awt.Color(255, 255, 255));
        c15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c15.setForeground(new java.awt.Color(0, 0, 0));
        c15.setText("C15");
        c15.setToolTipText("");
        c15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c15.setRolloverEnabled(false);
        c15.setSelectedIcon(b1.getSelectedIcon());
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });
        panel1.add(c15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c5.setForeground(new java.awt.Color(0, 0, 0));
        c5.setText("C5");
        c5.setToolTipText("");
        c5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c5.setRolloverEnabled(false);
        c5.setSelectedIcon(b1.getSelectedIcon());
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        panel1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        c10.setBackground(new java.awt.Color(255, 255, 255));
        c10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c10.setForeground(new java.awt.Color(0, 0, 0));
        c10.setText("C10");
        c10.setToolTipText("");
        c10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c10.setRolloverEnabled(false);
        c10.setSelectedIcon(b1.getSelectedIcon());
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        panel1.add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 0, 0));
        b8.setText("B8");
        b8.setToolTipText("");
        b8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b8.setRolloverEnabled(false);
        b8.setSelectedIcon(b1.getSelectedIcon());
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        panel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 0, 0));
        b7.setText("B7");
        b7.setToolTipText("");
        b7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b7.setRolloverEnabled(false);
        b7.setSelectedIcon(b1.getSelectedIcon());
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        panel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        b9.setBackground(new java.awt.Color(255, 255, 255));
        b9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b9.setForeground(new java.awt.Color(0, 0, 0));
        b9.setText("B9");
        b9.setToolTipText("");
        b9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b9.setRolloverEnabled(false);
        b9.setSelectedIcon(b1.getSelectedIcon());
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        panel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        b10.setBackground(new java.awt.Color(255, 255, 255));
        b10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b10.setForeground(new java.awt.Color(0, 0, 0));
        b10.setText("B10");
        b10.setToolTipText("");
        b10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b10.setRolloverEnabled(false);
        b10.setSelectedIcon(b1.getSelectedIcon());
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        panel1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        b12.setBackground(new java.awt.Color(255, 255, 255));
        b12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b12.setForeground(new java.awt.Color(0, 0, 0));
        b12.setText("B12");
        b12.setToolTipText("");
        b12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b12.setRolloverEnabled(false);
        b12.setSelectedIcon(b1.getSelectedIcon());
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        panel1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        b11.setBackground(new java.awt.Color(255, 255, 255));
        b11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b11.setForeground(new java.awt.Color(0, 0, 0));
        b11.setText("B11");
        b11.setToolTipText("");
        b11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b11.setRolloverEnabled(false);
        b11.setSelectedIcon(b1.getSelectedIcon());
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        panel1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 570, 30));

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c4.setForeground(new java.awt.Color(0, 0, 0));
        c4.setText("C4");
        c4.setToolTipText("");
        c4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c4.setRolloverEnabled(false);
        c4.setSelectedIcon(b1.getSelectedIcon());
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        panel1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        c9.setBackground(new java.awt.Color(255, 255, 255));
        c9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c9.setForeground(new java.awt.Color(0, 0, 0));
        c9.setText("C9");
        c9.setToolTipText("");
        c9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c9.setRolloverEnabled(false);
        c9.setSelectedIcon(b1.getSelectedIcon());
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });
        panel1.add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        c14.setBackground(new java.awt.Color(255, 255, 255));
        c14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c14.setForeground(new java.awt.Color(0, 0, 0));
        c14.setText("C14");
        c14.setToolTipText("");
        c14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c14.setRolloverEnabled(false);
        c14.setSelectedIcon(b1.getSelectedIcon());
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        panel1.add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        c13.setBackground(new java.awt.Color(255, 255, 255));
        c13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        c13.setForeground(new java.awt.Color(0, 0, 0));
        c13.setText("C13");
        c13.setToolTipText("");
        c13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        c13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        c13.setRolloverEnabled(false);
        c13.setSelectedIcon(b1.getSelectedIcon());
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });
        panel1.add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        a14.setBackground(new java.awt.Color(255, 255, 255));
        a14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a14.setForeground(new java.awt.Color(0, 0, 0));
        a14.setText("A14");
        a14.setToolTipText("");
        a14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a14.setRolloverEnabled(false);
        a14.setSelectedIcon(b1.getSelectedIcon());
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a14ActionPerformed(evt);
            }
        });
        panel1.add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        a9.setBackground(new java.awt.Color(255, 255, 255));
        a9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a9.setForeground(new java.awt.Color(0, 0, 0));
        a9.setText("A9");
        a9.setToolTipText("");
        a9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a9.setRolloverEnabled(false);
        a9.setSelectedIcon(b1.getSelectedIcon());
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        panel1.add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        a4.setBackground(new java.awt.Color(255, 255, 255));
        a4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("A4");
        a4.setToolTipText("");
        a4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a4.setRolloverEnabled(false);
        a4.setSelectedIcon(b1.getSelectedIcon());
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        panel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("A3");
        a3.setToolTipText("");
        a3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        a3.setRolloverEnabled(false);
        a3.setSelectedIcon(b1.getSelectedIcon());
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        panel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 0, 0));
        b5.setText("B5");
        b5.setToolTipText("");
        b5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/AsientoOcupado.png"))); // NOI18N
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/Asiento.png"))); // NOI18N
        b5.setRolloverEnabled(false);
        b5.setSelectedIcon(b1.getSelectedIcon());
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        panel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed

    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed

    }//GEN-LAST:event_b12ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed

    }//GEN-LAST:event_b10ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
    }//GEN-LAST:event_b9ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
    }//GEN-LAST:event_b8ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed

    }//GEN-LAST:event_c10ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
    }//GEN-LAST:event_c5ActionPerformed

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed

    }//GEN-LAST:event_c15ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
    }//GEN-LAST:event_c8ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
    }//GEN-LAST:event_c3ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed

    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed

    }//GEN-LAST:event_c12ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
    }//GEN-LAST:event_c7ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
    }//GEN-LAST:event_c6ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
    }//GEN-LAST:event_c2ActionPerformed

    private void a10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a10ActionPerformed

    }//GEN-LAST:event_a10ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
    }//GEN-LAST:event_a5ActionPerformed

    private void a15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a15ActionPerformed

    }//GEN-LAST:event_a15ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
    }//GEN-LAST:event_a8ActionPerformed

    private void a13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a13ActionPerformed

    }//GEN-LAST:event_a13ActionPerformed

    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed

    }//GEN-LAST:event_a11ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed

    }//GEN-LAST:event_a12ActionPerformed

    private void a7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a7ActionPerformed
    }//GEN-LAST:event_a7ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
    }//GEN-LAST:event_a6ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
    }//GEN-LAST:event_a2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
    }//GEN-LAST:event_b6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    }//GEN-LAST:event_b5ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
    }//GEN-LAST:event_a4ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
    }//GEN-LAST:event_a9ActionPerformed

    private void a14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a14ActionPerformed

    }//GEN-LAST:event_a14ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed

    }//GEN-LAST:event_c13ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
    }//GEN-LAST:event_c4ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
    }//GEN-LAST:event_c9ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        
    }//GEN-LAST:event_c14ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirAsiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirAsiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirAsiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirAsiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirAsiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox a1;
    private javax.swing.JCheckBox a10;
    private javax.swing.JCheckBox a11;
    private javax.swing.JCheckBox a12;
    private javax.swing.JCheckBox a13;
    private javax.swing.JCheckBox a14;
    private javax.swing.JCheckBox a15;
    private javax.swing.JCheckBox a2;
    private javax.swing.JCheckBox a3;
    private javax.swing.JCheckBox a4;
    private javax.swing.JCheckBox a5;
    private javax.swing.JCheckBox a6;
    private javax.swing.JCheckBox a7;
    private javax.swing.JCheckBox a8;
    private javax.swing.JCheckBox a9;
    private javax.swing.JCheckBox b1;
    private javax.swing.JCheckBox b10;
    private javax.swing.JCheckBox b11;
    private javax.swing.JCheckBox b12;
    private javax.swing.JCheckBox b2;
    private javax.swing.JCheckBox b3;
    private javax.swing.JCheckBox b4;
    private javax.swing.JCheckBox b5;
    private javax.swing.JCheckBox b6;
    private javax.swing.JCheckBox b7;
    private javax.swing.JCheckBox b8;
    private javax.swing.JCheckBox b9;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c12;
    private javax.swing.JCheckBox c13;
    private javax.swing.JCheckBox c14;
    private javax.swing.JCheckBox c15;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
