/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

public class Reportes extends javax.swing.JFrame {

    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel17 = new java.awt.Panel();
        panel16 = new java.awt.Panel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReporte = new javax.swing.JTable();
        comboBoxDia = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        comboBoxMes = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        txtVentaPromedio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel17.setBackground(new java.awt.Color(255, 255, 254));
        panel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel16.setBackground(new java.awt.Color(25, 43, 55));

        jLabel20.setBackground(new java.awt.Color(25, 43, 55));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reporte de ventas");

        javax.swing.GroupLayout panel16Layout = new javax.swing.GroupLayout(panel16);
        panel16.setLayout(panel16Layout);
        panel16Layout.setHorizontalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel16Layout.createSequentialGroup()
                .addContainerGap(563, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(16, 16, 16))
        );
        panel16Layout.setVerticalGroup(
            panel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel17.add(panel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 50));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 43, 55));
        jLabel13.setText("Dia");
        panel17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setToolTipText("Regresar");
        panel17.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 90, 30));

        tableReporte.setAutoCreateRowSorter(true);
        tableReporte.setBackground(new java.awt.Color(255, 255, 255));
        tableReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. de Venta", "Fecha ", "Obra", "Boletos", "T. Vendido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableReporte.setShowGrid(true);
        jScrollPane2.setViewportView(tableReporte);
        if (tableReporte.getColumnModel().getColumnCount() > 0) {
            tableReporte.getColumnModel().getColumn(0).setResizable(false);
            tableReporte.getColumnModel().getColumn(1).setResizable(false);
            tableReporte.getColumnModel().getColumn(2).setResizable(false);
            tableReporte.getColumnModel().getColumn(3).setResizable(false);
            tableReporte.getColumnModel().getColumn(4).setResizable(false);
        }

        panel17.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 480, 370));

        comboBoxDia.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxDia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxDia.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxDia.setMaximumRowCount(5);
        comboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un dia-" }));
        comboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDiaActionPerformed(evt);
            }
        });
        panel17.add(comboBoxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 200, 30));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 43, 55));
        jLabel14.setText("Mes");
        panel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        comboBoxMes.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxMes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboBoxMes.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxMes.setMaximumRowCount(4);
        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione un mes-", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        comboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMesActionPerformed(evt);
            }
        });
        panel17.add(comboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 200, 30));

        btnBuscar.setBackground(btnRegresar.getBackground());
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panel17.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 200, 30));

        txtVentaPromedio.setEditable(false);
        txtVentaPromedio.setBackground(new java.awt.Color(255, 255, 255));
        panel17.add(txtVentaPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 200, 30));

        jLabel1.setFont(jLabel13.getFont());
        jLabel1.setForeground(new java.awt.Color(25, 43, 55));
        jLabel1.setText("Venta Promedio");
        panel17.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        getContentPane().add(panel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        panel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 740, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxDiaActionPerformed

    private void comboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxMesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    public JTextField getTxtVentaPromedio() {
        return txtVentaPromedio;
    }

    public void setTxtVentaPromedio(JTextField txtVentaPromedio) {
        this.txtVentaPromedio = txtVentaPromedio;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }

    public JComboBox<String> getComboBoxDia() {
        return comboBoxDia;
    }

    public void setComboBoxDia(JComboBox<String> comboBoxDia) {
        this.comboBoxDia = comboBoxDia;
    }

    public JComboBox<String> getComboBoxMes() {
        return comboBoxMes;
    }

    public void setComboBoxMes(JComboBox<String> comboBoxMes) {
        this.comboBoxMes = comboBoxMes;
    }

    public JTable getTableReporte() {
        return tableReporte;
    }

    public void setTableReporte(JTable tableReporte) {
        this.tableReporte = tableReporte;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboBoxDia;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel16;
    private java.awt.Panel panel17;
    private java.awt.Panel panel4;
    private javax.swing.JTable tableReporte;
    private javax.swing.JTextField txtVentaPromedio;
    // End of variables declaration//GEN-END:variables
}
