/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author diana
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTicket
     */
    public Ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numVenta = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        funcion = new javax.swing.JLabel();
        label8 = new java.awt.Label();
        lineas = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        boletos = new javax.swing.JLabel();
        lineas1 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        boletos1 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        boletos2 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        boletos3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ticket");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        numVenta.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        numVenta.setForeground(new java.awt.Color(0, 0, 0));
        numVenta.setText("000000000");

        a.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a.setForeground(new java.awt.Color(0, 0, 0));
        a.setText("Funcion:");

        funcion.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        funcion.setForeground(new java.awt.Color(0, 0, 0));
        funcion.setText("Alicia en el pais de las maravillas");

        label8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 153, 0));
        label8.setText("CHACHITA");

        lineas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lineas.setForeground(new java.awt.Color(0, 0, 0));
        lineas.setText("--------------------------------------------------------------");

        a1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a1.setForeground(new java.awt.Color(0, 0, 0));
        a1.setText("Fecha:");

        fecha.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setText("12/12/12");

        a3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a3.setForeground(new java.awt.Color(0, 0, 0));
        a3.setText("Hora:");

        hora.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        hora.setForeground(new java.awt.Color(0, 0, 0));
        hora.setText("15hrs");

        a4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a4.setForeground(new java.awt.Color(0, 0, 0));
        a4.setText("Boletos:");

        boletos.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        boletos.setForeground(new java.awt.Color(0, 0, 0));
        boletos.setText("A1-3, A6, B7");

        lineas1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lineas1.setForeground(new java.awt.Color(0, 0, 0));
        lineas1.setText("--------------------------------------------------------------");

        a6.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a6.setForeground(new java.awt.Color(0, 0, 0));
        a6.setText("Precio:");

        boletos1.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        boletos1.setForeground(new java.awt.Color(0, 0, 0));
        boletos1.setText("$100");

        a7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a7.setForeground(new java.awt.Color(0, 0, 0));
        a7.setText("Entrega:");

        boletos2.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        boletos2.setForeground(new java.awt.Color(0, 0, 0));
        boletos2.setText("$200");

        a8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        a8.setForeground(new java.awt.Color(0, 0, 0));
        a8.setText("Cambio:");

        boletos3.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        boletos3.setForeground(new java.awt.Color(0, 0, 0));
        boletos3.setText("$100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lineas)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funcion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hora))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boletos))
                            .addComponent(lineas1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boletos1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boletos3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(a7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(boletos2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(numVenta)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(numVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lineas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a)
                    .addComponent(funcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a1)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a3)
                    .addComponent(hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a4)
                    .addComponent(boletos))
                .addGap(1, 1, 1)
                .addComponent(lineas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a6)
                    .addComponent(boletos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a7)
                    .addComponent(boletos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a8)
                    .addComponent(boletos3))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel boletos;
    private javax.swing.JLabel boletos1;
    private javax.swing.JLabel boletos2;
    private javax.swing.JLabel boletos3;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel funcion;
    private javax.swing.JLabel hora;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label8;
    private javax.swing.JLabel lineas;
    private javax.swing.JLabel lineas1;
    private javax.swing.JLabel numVenta;
    // End of variables declaration//GEN-END:variables
}
